export const images = [
  {
    name: "Hidden_Valley_Ranch",
    url: "https://i.imgur.com/41jmX2F.gif",
    number: 1,
    // fullName: "HIDDEN VALLEY RANCH - HOW WOULD THEY KNOW",
    fullName: "HIDDEN VALLEY RANCH ",
    details: {
      director: "Alice Kong",
      director_of_photography: "Charlie Sarroff",
      producer: "DENTSU / Partizan / Tonic",
      production_designer: "SupervisingArtDirector",
      art_directors: "ArtDirectors",
      year: 2022,
      videoUrl: [
        "https://player.vimeo.com/video/918725720?h=628ae8424e&byline=0&portrait=0",
        "https://player.vimeo.com/video/918729922?h=9f8c0cd62f&byline=0&portrait=0",
        "https://player.vimeo.com/video/918730816?h=180b30f6af&byline=0&portrait=0",
        "https://player.vimeo.com/video/918731344?h=fb1a1b6ad1&byline=0&portrait=0",
        "https://player.vimeo.com/video/918725720?h=628ae8424e&byline=0&portrait=0",
        "https://player.vimeo.com/video/918729922?h=9f8c0cd62f&byline=0&portrait=0",
        "https://player.vimeo.com/video/918730816?h=180b30f6af&byline=0&portrait=0",
        "https://player.vimeo.com/video/918731344?h=fb1a1b6ad1&byline=0&portrait=0",
        "https://player.vimeo.com/video/918725720?h=628ae8424e&byline=0&portrait=0",
        "https://player.vimeo.com/video/918729922?h=9f8c0cd62f&byline=0&portrait=0",
        "https://player.vimeo.com/video/918730816?h=180b30f6af&byline=0&portrait=0",
        "https://player.vimeo.com/video/918731344?h=fb1a1b6ad1&byline=0&portrait=0",
        //____________
      ],
      productionImages: [
        // "https://media.self.com/photos/617aaa21128425bd603b0763/1:1/w_960,h_960,c_limit",
        // "https://i0.wp.com/www.rblandmark.com/wp-content/uploads/2023/02/Jontu-gorilla-1.jpg?fit=1200%2C857&quality=89&ssl=1",
        // "https://nationalzoo.si.edu/sites/default/files/animals/lowlandgorilla-002.jpg",
        // "https://i0.wp.com/www.rblandmark.com/wp-content/uploads/2023/02/Jontu-gorilla-1.jpg?fit=1200%2C857&quality=89&ssl=1",
        // "https://media.self.com/photos/617aaa21128425bd603b0763/1:1/w_960,h_960,c_limit",
        // "https://i0.wp.com/www.rblandmark.com/wp-content/uploads/2023/02/Jontu-gorilla-1.jpg?fit=1200%2C857&quality=89&ssl=1",
        // "https://nationalzoo.si.edu/sites/default/files/animals/lowlandgorilla-002.jpg",
        // "https://i0.wp.com/www.rblandmark.com/wp-content/uploads/2023/02/Jontu-gorilla-1.jpg?fit=1200%2C857&quality=89&ssl=1",
        // "https://media.self.com/photos/617aaa21128425bd603b0763/1:1/w_960,h_960,c_limit",
        // "https://i0.wp.com/www.rblandmark.com/wp-content/uploads/2023/02/Jontu-gorilla-1.jpg?fit=1200%2C857&quality=89&ssl=1",
        // "https://nationalzoo.si.edu/sites/default/files/animals/lowlandgorilla-002.jpg",
        // "https://i0.wp.com/www.rblandmark.com/wp-content/uploads/2023/02/Jontu-gorilla-1.jpg?fit=1200%2C857&quality=89&ssl=1",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-3.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-4.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-5.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-6.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-7.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-8.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-9.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-10.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-11.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-12.jpg",
      ],
    },
  },
  {
    name: "current_backwards_twisted",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 2,
    fullName: "CURRENT - BACKWARDS, TWISTED",
    details: {
      director: "Matt Swanson",
      director_of_photography: "Damian Acevedo",
      producer: "Current / Epoch / Flo films",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2023,
      videoUrl: [
        "https://player.vimeo.com/video/918735116?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918735576?h=633e835c37&byline=0&portrait=0",
        "https://player.vimeo.com/video/918736244?h=b23b31b42a&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-3.jpg",
      ],
    },
  },
  {
    name: "aig",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 3,
    fullName: "AIG - Action is Everything",
    details: {
      director: "Jaron Albertin",
      director_of_photography: " Agustin Claramunt",
      producer: "HUGE / Smuggler / Habitant",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2022,
      videoUrl: [
        "https://player.vimeo.com/video/918741009?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918741009?h=7d1b9540b0&byline=0&portrait=0",
        // "https://player.vimeo.com/video/918741009?h=7d1b9540b0&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
      ],
    },
  },
  {
    name: "smartfood",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 4,
    fullName: "SMARTFOOD",
    details: {
      director: "MaMa - Mark Potoka & Matt Spicer",
      director_of_photography: "Javier Zarco",
      producer: "GS&P / World War Seven / Story WeProduce:)",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2022,
      videoUrl: [
        "https://player.vimeo.com/video/918745129?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918745376?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918745376?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918745507?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918754944?h=7d1b9540b0&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-3.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-4.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-5.jpg",
      ],
    },
  },
  {
    name: "jimador_reservado_para_todos",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 5,
    fullName: "JIMADOR - El Jimador es Reservado para todos",
    details: {
      director: "Beatriz Sanchis",
      director_of_photography: "Lluís Martí",
      producer: "El Jimador / ENERGY BBDO / Easy Mondays",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2022,
      videoUrl: [
        "https://player.vimeo.com/video/918754944?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918754944?h=7d1b9540b0&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
      ],
    },
  },
  {
    name: "square",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 6,
    fullName: "SQUARE",
    details: {
      director: "Andrew Batista",
      director_of_photography: "Lluis Martí",
      producer: "Strike anywhere / Landia / Global Production Network",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2022,
      videoUrl: [
        "https://player.vimeo.com/video/918754944?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918754944?h=7d1b9540b0&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
      ],
    },
  },
  {
    name: "pinch_a_penny",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 7,
    fullName: "PINCH A PENNY - The Pool's Always Open",
    details: {
      director: "Sammuel & Gunnar",
      director_of_photography: "Sean Baggley",
      producer: "BSP / TRG / FLO FILMS",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2023,
      videoUrl: [
        "https://player.vimeo.com/video/918757295?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918757295?h=7d1b9540b0&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
      ],
    },
  },
  {
    name: "colgate_optic_white",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 8,
    fullName: "Discover the secret to a brighter smile",
    details: {
      director: "Ace Norton",
      director_of_photography: "Stephen McGehee / Javier Zarco",
      producer: "MCA / WPP RED FUSE / JOX ",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2023,
      videoUrl: [
        "https://player.vimeo.com/video/918757999?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918758229?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918758324?h=7d1b9540b0&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-3.jpg",
      ],
    },
  },
  {
    name: "us_open",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 9,
    fullName: "US OPEN - ESPN",
    details: {
      director: "Gásparo Daniel",
      director_of_photography: "Esteban Robles",
      producer: "ESPN / DFLA Films ",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2019,
      videoUrl: [
        "https://player.vimeo.com/video/918758790?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918758790?h=7d1b9540b0&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
      ],
    },
  },
  {
    name: "chateau_ste_michelle",
    url: "https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg",
    number: 10,
    fullName: "CHATEAU STE MICHELLE - Lake House",
    details: {
      director: "The Selby",
      director_of_photography: "The Selby",
      producer: "Team One / The Selby / StoryWeProduce:) ",
      // production_designer: "SupervisingArtDirector",
      // art_directors: "ArtDirectors",
      year: 2021,
      videoUrl: [
        "https://player.vimeo.com/video/918759629?h=7d1b9540b0&byline=0&portrait=0",
        "https://player.vimeo.com/video/918759397?h=7d1b9540b0&byline=0&portrait=0",
      ],
      productionImages: [
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-1.jpg",
        "https://gamedata.britishcouncil.org/sites/default/files/attachment/number-2.jpg",
      ],
    },
  },
];
